# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cupo_maximo', models.IntegerField(default=20)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='fecha de publicación')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_miembro', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gimnasio.clase')),
            ],
        ),
    ]
