# Generated by Django 6.1.1 on 2026-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='sede',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
